### ISSUE TITLE
Перенести считывание всех изображений в onResume.

### ISSUE THREAD

**Issue by IlyaMatveev007** [HadronCollider/sirius22-android#46]
Не обязательная задача. При чтении большого количества изображений активити проекта долго запускается. Лучше считать все изображения и сделать недостающие маленькие после отображения всех изображений, а на месте списка сделать спинер, пока изображения не были загружены.

**Comment by Jengle88** [comment]
Это нужно делать не в onResume, а в отдельном потоке. Иначе ты просто main поток тормозишь на загрузку изображений. При больших данных у тебя вообще должно падать приложение, ибо нельзя на долго стопорить main поток
